site_name: Scratch works and Scratch works
site_url: https://mydomain.org/mysite
theme:
  name: material
plugins:
  - blog
  - search
  - mermaid2
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: ''
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
      # auto_append:
        # - includes/abbreviations.md
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - index.md
  - Blog:
    - Engines:
      - blog/index.md
      - blog/Basical Naming Rules/index.md
      - blog/Black Screens/index.md
      - blog/URM/index.md
      - blog/Colorful Costumes/index.md
      - blog/Input Gathering/index.md
      - blog/Frame Skipping/index.md
      - blog/Event Attached/index.md
    - Projects:
      - blog/Project Analysis/index.md
